<script setup>
import { computed, defineAsyncComponent, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { RouterLink, useRouter } from 'vue-router'
import CitySearch from '../components/CitySearch.vue'
import Icon3D from '../components/Icon3D.vue'
import { aqiCategory, categoryStyle } from '../lib/aqi'
import { tilt as vTilt } from '../lib/tilt'

// Three.js is large; load it only for the landing page hero.
const HeroScene3D = defineAsyncComponent(() => import('../components/landing/HeroScene3D.vue'))

const router = useRouter()
const reducedMotion = typeof window !== 'undefined'
  && window.matchMedia('(prefers-reduced-motion: reduce)').matches

function openCity(place) {
  router.push({
    name: 'dashboard',
    query: { city: place.name, region: place.region || undefined, lat: place.lat, lon: place.lon },
  })
}

// ---------- live snapshot (ticker + counters) ----------
const snapshot = ref(null)
onMounted(async () => {
  try {
    const res = await fetch('/api/snapshot')
    if (res.ok) snapshot.value = await res.json()
  } catch { /* the page still works without live numbers */ }
})

const delhi = computed(() => snapshot.value?.cities.find((c) => c.name === 'New Delhi'))

// ---------- smog vision ----------
const smog = ref(0)
const smogLabel = computed(() => (smog.value ? aqiCategory(smog.value) : 'Clean air'))
const smogStyle = computed(() => categoryStyle(smog.value ? aqiCategory(smog.value) : 'Good'))
const smogPresets = computed(() => {
  const live = (snapshot.value?.cities || [])
    .filter((c) => ['New Delhi', 'Ludhiana'].includes(c.name))
    .map((c) => ({ label: `${c.name.replace('New ', '')} now`, aqi: c.aqi }))
  return [{ label: 'Clean', aqi: 0 }, ...live, { label: 'Severe day', aqi: 450 }]
})

// Count-up for the fire stat, once it is both on screen and loaded.
const statsEl = ref(null)
const statsVisible = ref(false)
const shownFires = ref(null) // null = show the real number (no animation yet)
let io = null
let raf = 0

onMounted(() => {
  io = new IntersectionObserver(([entry]) => {
    if (entry.isIntersecting) { statsVisible.value = true; io.disconnect() }
  }, { threshold: 0.4 })
  io.observe(statsEl.value)
})

watch([statsVisible, () => snapshot.value?.fires_48h_punjab_haryana], ([visible, target]) => {
  if (!visible || target == null) return
  if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) {
    shownFires.value = target
    return
  }
  const start = performance.now()
  const step = (t) => {
    const p = Math.min((t - start) / 1200, 1)
    shownFires.value = Math.round(target * (1 - (1 - p) ** 3)) // ease-out
    if (p < 1) raf = requestAnimationFrame(step)
  }
  raf = requestAnimationFrame(step)
})

onBeforeUnmount(() => { io?.disconnect(); cancelAnimationFrame(raf) })

// ---------- content ----------
const FEATURES = [
  { icon: 'fire', title: 'Smoke Trail & Radar', section: 'smoke', view: 'radar',
    text: 'Trace your air back 48 hours, or watch a time-lapse of fires, wind and smoke drifting across North India.' },
  { icon: 'wind_face', title: 'Incoming Smoke Alert', section: 'smoke', view: 'coming',
    text: 'Runs today\'s satellite-detected fires forward on forecast winds to estimate when smoke may reach your city.' },
  { icon: 'school', title: 'School Mode + parent notices', section: 'school',
    text: 'UrbanWise guidance (go, limit or cancel) for assembly, PE and dismissal — and a notice to parents in English, Hindi and Punjabi.' },
  { icon: 'face_with_medical_mask', title: 'Today\'s air & forecast', section: '',
    text: 'India\'s CPCB AQI scale applied to CAMS model estimates, plain-language advice, and the best and worst hours to be outside.' },
  { icon: 'lungs', title: 'Your exposure', section: 'health',
    text: 'How much pollution you\'ll breathe in, shown as a cigarette equivalent — plus when to open windows.' },
  { icon: 'speech_balloon', title: 'Ask UrbanWise', section: 'ask',
    text: 'Ask by voice or text, in English, हिंदी or ਪੰਜਾਬੀ — and hear the answer read aloud.' },
]

const STEPS = [
  { icon: 'satellite', title: 'Satellites & sensors', text: 'NASA fire detections, CAMS air-quality forecasts and wind data, refreshed hourly.' },
  { icon: 'chart_increasing', title: 'UrbanWise connects them', text: 'CPCB-scale AQI, smoke back- and forward-tracking, and School Mode guidance based on CPCB categories.' },
  { icon: 'school', title: 'You act', text: 'Clear decisions for today and tomorrow — and a notice ready to send.' },
]

// A real notice generated by UrbanWise (Gemini wording, UrbanWise facts),
// trimmed for the showcase.
const SAMPLE = {
  en: `Dear Parents,

On 9 October 2026, we will follow our normal schedule with extra care for children with asthma or breathing problems.

Please ensure your child carries their inhaler if needed and stays well-hydrated today.

Principal, Green Valley Public School`,
  hi: `प्रिय अभिभावकगण,

9 अक्टूबर 2026 को, हम अस्थमा या सांस की समस्याओं वाले बच्चों की अतिरिक्त देखभाल के साथ सामान्य समय-सारणी का पालन करेंगे।

कृपया सुनिश्चित करें कि आपका बच्चा अपना इनहेलर साथ रखे और आज पर्याप्त पानी पिए।

प्रिंसिपल, ग्रीन वैली पब्लिक स्कूल`,
  pa: `ਪਿਆਰੇ ਮਾਪਿਓ,

9 ਅਕਤੂਬਰ 2026 ਨੂੰ, ਅਸੀਂ ਅਸਥਮਾ ਜਾਂ ਸਾਹ ਦੀਆਂ ਤਕਲੀਫਾਂ ਵਾਲੇ ਬੱਚਿਆਂ ਦੀ ਵਧੇਰੇ ਦੇਖਭਾਲ ਦੇ ਨਾਲ ਆਪਣਾ ਆਮ ਸ਼ਡਿਊਲ ਅਪਣਾਵਾਂਗੇ।

ਕਿਰਪਾ ਕਰਕੇ ਯਕੀਨੀ ਬਣਾਓ ਕਿ ਤੁਹਾਡਾ ਬੱਚਾ ਆਪਣਾ ਇਨਹੇਲਰ ਨਾਲ ਰੱਖੇ ਅਤੇ ਅੱਜ ਲੋੜੀਂਦਾ ਪਾਣੀ ਪੀਵੇ।

ਪ੍ਰਿੰਸੀਪਲ, ਗ੍ਰੀਨ ਵੈਲੀ ਪਬਲਿਕ ਸਕੂਲ`,
}
const sampleLang = ref('en')
const LANGS = [['en', 'English'], ['hi', 'हिंदी'], ['pa', 'ਪੰਜਾਬੀ']]
</script>

<template>
  <div class="landing">
    <!-- NAV -->
    <header class="nav">
      <RouterLink to="/" class="brand">
        <img src="/favicon.svg" alt="" width="34" height="34" />
        <strong>UrbanWise</strong>
      </RouterLink>
      <nav class="links">
        <a href="#features">Features</a>
        <a href="#how">How it works</a>
        <a href="#schools">For schools</a>
      </nav>
      <RouterLink :to="{ name: 'dashboard' }" class="btn btn-primary">Open dashboard</RouterLink>
    </header>

    <!-- HERO -->
    <section class="hero">
      <div class="hero-copy">
        <p class="eyebrow">Bad-air-day assistant for Indian cities</p>
        <h1>
          Know your air.<br />
          <span class="hl-navy">Know where it comes from.</span><br />
          <span class="hl-orange">Know what to do.</span>
        </h1>
        <p class="lede">
          Air-quality estimates, the satellite-detected fires your smoke likely passed, and clear
          guidance for families and schools — in English, हिंदी and ਪੰਜਾਬੀ.
        </p>
        <div class="search-row">
          <CitySearch @select="openCity" />
        </div>
        <p v-if="delhi" class="live-chip">
          <span class="dot" :style="{ background: categoryStyle(delhi.category).bg }"></span>
          Delhi now (model estimate): <strong>AQI {{ delhi.aqi }} · {{ delhi.category }}</strong>
        </p>
      </div>
      <div class="hero-scene">
        <HeroScene3D :aqi="smog" />
        <div class="smog">
          <div class="smog-head">
            <strong>😶‍🌫️ Smog vision</strong>
            <span class="smog-badge" :style="{ background: smogStyle.bg, color: smogStyle.fg }">
              {{ smog ? `AQI ${smog}` : 'AQI 0' }} · {{ smogLabel }}
            </span>
          </div>
          <label class="visually-hidden" for="smog-range">Air quality to show in the 3D city</label>
          <input id="smog-range" v-model.number="smog" type="range" min="0" max="500" step="5" />
          <div class="smog-presets">
            <button
              v-for="p in smogPresets"
              :key="p.label"
              type="button"
              :class="{ on: smog === p.aqi }"
              @click="smog = p.aqi"
            >{{ p.label }}<small v-if="p.aqi"> {{ p.aqi }}</small></button>
          </div>
        </div>
      </div>
    </section>

    <!-- LIVE TICKER -->
    <section v-if="snapshot?.cities.length" class="ticker" aria-label="Latest model estimates of air quality in North Indian cities">
      <span class="ticker-label" title="Latest CAMS model estimates, refreshed every 15 minutes">● LATEST ESTIMATES</span>
      <div class="ticker-track">
        <div class="ticker-items">
          <!-- The second copy only exists to loop the marquee seamlessly. -->
          <template v-for="copy in (reducedMotion ? 1 : 2)" :key="copy">
            <button
              v-for="c in snapshot.cities"
              :key="`${copy}-${c.name}`"
              type="button"
              class="ticker-item"
              :aria-hidden="copy === 2 ? 'true' : undefined"
              :tabindex="copy === 2 ? -1 : 0"
              @click="openCity(c)"
            >
              <span class="pill" :style="{ background: categoryStyle(c.category).bg, color: categoryStyle(c.category).fg }">{{ c.aqi }}</span>
              {{ c.name }} <small>{{ c.category }}</small>
            </button>
          </template>
        </div>
      </div>
    </section>

    <!-- STATS -->
    <section ref="statsEl" class="stats">
      <div class="stat card">
        <Icon3D name="fire" :size="52" />
        <div>
          <p class="num">{{ shownFires ?? snapshot?.fires_48h_punjab_haryana ?? '—' }}</p>
          <p class="muted small">fires detected by satellite in Punjab &amp; Haryana in the last 48 hours</p>
        </div>
      </div>
      <div class="stat card">
        <Icon3D name="wind_face" :size="52" :delay="1" />
        <div>
          <p class="num">48 h</p>
          <p class="muted small">of wind traced backwards to find where your smoke came from</p>
        </div>
      </div>
      <div class="stat card">
        <Icon3D name="speech_balloon" :size="52" :delay="2" />
        <div>
          <p class="num">3</p>
          <p class="muted small">languages for notices and answers: English, हिंदी, ਪੰਜਾਬੀ</p>
        </div>
      </div>
    </section>

    <!-- FEATURES -->
    <section id="features" class="block">
      <p class="eyebrow center">Everything for a bad-air day</p>
      <h2 class="center">One place to understand the air — and act on it</h2>
      <div class="features">
        <RouterLink
          v-for="(f, i) in FEATURES"
          :key="f.title"
          v-tilt="6"
          :to="{ name: 'dashboard', params: { section: f.section }, query: f.view ? { view: f.view } : {} }"
          class="card feature"
        >
          <div class="feature-icon"><Icon3D :name="f.icon" :size="64" :delay="i * 0.6" /></div>
          <h3>{{ f.title }}</h3>
          <p class="muted">{{ f.text }}</p>
          <span class="go">Try it →</span>
        </RouterLink>
      </div>
    </section>

    <!-- HOW IT WORKS -->
    <section id="how" class="block">
      <p class="eyebrow center">How it works</p>
      <h2 class="center">From satellites to a decision in seconds</h2>
      <ol class="steps">
        <li v-for="(s, i) in STEPS" :key="s.title" class="step">
          <div class="step-icon"><Icon3D :name="s.icon" :size="72" :delay="i" /></div>
          <span class="step-num">{{ i + 1 }}</span>
          <h3>{{ s.title }}</h3>
          <p class="muted">{{ s.text }}</p>
        </li>
      </ol>
    </section>

    <!-- SCHOOLS -->
    <section id="schools" class="block schools">
      <div class="schools-copy">
        <p class="eyebrow">For schools</p>
        <h2>Tomorrow's decision, and the message to parents — done</h2>
        <ul class="checks">
          <li>Checks assembly, PE and dismissal against that hour's forecast</li>
          <li>Based on India's CPCB AQI categories (GRAP stages shown for Delhi-NCR)</li>
          <li>Writes the notice in English, Hindi and Punjabi — you review and share</li>
        </ul>
        <RouterLink :to="{ name: 'dashboard', params: { section: 'school' } }" class="btn btn-accent">Try School Mode</RouterLink>
      </div>
      <div v-tilt="5" class="card notice">
        <div class="notice-head">
          <Icon3D name="envelope_with_arrow" :size="40" />
          <strong>Example notice written by UrbanWise</strong>
        </div>
        <div class="tabs" role="group" aria-label="Notice language">
          <button
            v-for="[id, label] in LANGS"
            :key="id"
            type="button"
            :aria-pressed="sampleLang === id"
            :class="{ active: sampleLang === id }"
            @click="sampleLang = id"
          >{{ label }}</button>
        </div>
        <p class="notice-text" :lang="sampleLang">{{ SAMPLE[sampleLang] }}</p>
        <RouterLink :to="{ name: 'dashboard', params: { section: 'school' } }" class="wa">Write one for your school →</RouterLink>
      </div>
    </section>

    <!-- CTA -->
    <section class="cta card">
      <Icon3D name="cityscape" :size="96" />
      <div>
        <h2>How's the air in your city?</h2>
        <p class="muted">Search any Indian city to see its air, its smoke trail and what to do.</p>
      </div>
      <RouterLink :to="{ name: 'dashboard' }" class="btn btn-primary">Open dashboard</RouterLink>
    </section>

    <footer class="footer small muted">
      <p>
        Built for Environmental Hacks — Bharat Builds Tour, Track 1: Air. UrbanWise gives estimates
        for planning, not medical advice. Air-quality values are CAMS model estimates, not station
        measurements; smoke paths and arrival times are model-based estimates.
      </p>
      <p>
        Data: Open-Meteo (CAMS air-quality forecasts, winds), NASA FIRMS (fire detections),
        CPCB (AQI bands), CAQM (GRAP). Map © OpenStreetMap contributors.
        3D icons: Microsoft Fluent Emoji (MIT).
      </p>
      <p>
        <RouterLink :to="{ name: 'dashboard', query: { replay: '2026-10-08' } }">▶ Demo replay — real data captured 8 Oct 2026</RouterLink>
      </p>
    </footer>
  </div>
</template>

<style scoped>
.landing {
  max-width: 1180px;
  margin: 0 auto;
  padding: 0 20px 32px;
}

/* NAV */
.nav {
  position: sticky;
  top: 10px;
  z-index: 50;
  display: flex;
  align-items: center;
  gap: 24px;
  margin: 10px 0 0;
  padding: 10px 14px 10px 16px;
  border: 1px solid var(--border);
  border-radius: 18px;
  background: rgba(255, 255, 255, 0.82);
  backdrop-filter: blur(12px);
  box-shadow: 0 8px 24px -14px rgba(23, 33, 58, 0.35);
}

.brand { display: flex; align-items: center; gap: 10px; color: var(--brand); text-decoration: none; font-size: 1.15rem; }

.links { display: flex; gap: 22px; margin-left: auto; }

.links a { color: var(--muted); text-decoration: none; font-weight: 600; }

.links a:hover { color: var(--brand); }

/* HERO */
.hero {
  display: grid;
  grid-template-columns: minmax(0, 1fr) minmax(0, 1.05fr);
  align-items: center;
  gap: 24px;
  min-height: 560px;
  padding: 36px 0 12px;
}

.eyebrow {
  margin: 0 0 10px;
  color: var(--accent-ink);
  font-size: 0.8rem;
  font-weight: 700;
  letter-spacing: 0.08em;
  text-transform: uppercase;
}

.eyebrow.center, h2.center { text-align: center; }

h1 {
  margin: 0 0 16px;
  font-size: clamp(2.1rem, 4.6vw, 3.5rem);
  line-height: 1.08;
  letter-spacing: -0.02em;
}

.hl-navy { color: var(--brand); }

.hl-orange {
  /* Both ends ≥4.3:1 on white (the old #FF9F5A end was 2:1). */
  background: linear-gradient(90deg, #D9480F, #B54708);
  -webkit-background-clip: text;
  background-clip: text;
  color: transparent;
}

.lede { margin: 0 0 22px; color: var(--muted); font-size: 1.1rem; max-width: 48ch; }

.search-row :deep(.search) { max-width: 420px; }

.search-row :deep(input) {
  padding: 14px 18px;
  border-radius: 14px;
  font-size: 1.02rem;
  box-shadow: 0 10px 26px -14px rgba(34, 53, 122, 0.45);
}

.live-chip {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  margin: 16px 0 0;
  padding: 7px 14px;
  border: 1px solid var(--border);
  border-radius: 999px;
  background: var(--surface);
}

.dot { width: 10px; height: 10px; border-radius: 50%; animation: ping 2.2s ease-out infinite; }

@keyframes ping {
  0% { box-shadow: 0 0 0 0 rgba(242, 106, 27, 0.45); }
  80%, 100% { box-shadow: 0 0 0 10px transparent; }
}

.hero-scene {
  position: relative;
  height: 520px;
  border-radius: 32px;
  background:
    radial-gradient(60% 60% at 50% 45%, #FFFFFF, transparent 70%),
    linear-gradient(160deg, #E3ECFF 0%, #FDF0E6 100%);
  box-shadow: inset 0 0 0 1px #E3E9F6, 0 30px 60px -40px rgba(34, 53, 122, 0.55);
  overflow: hidden;
}

/* SMOG VISION */
.smog {
  position: absolute;
  left: 14px;
  right: 14px;
  bottom: 14px;
  padding: 12px 14px;
  border: 1px solid rgba(255, 255, 255, 0.7);
  border-radius: 16px;
  background: rgba(255, 255, 255, 0.78);
  backdrop-filter: blur(10px);
  box-shadow: 0 10px 24px -14px rgba(23, 33, 58, 0.45);
}

.smog-head { display: flex; justify-content: space-between; align-items: center; gap: 8px; flex-wrap: wrap; }

.smog-badge { padding: 2px 10px; border-radius: 999px; font-size: 0.82rem; font-weight: 700; }

.smog input[type='range'] {
  width: 100%;
  margin: 8px 0 6px;
  accent-color: var(--accent);
}

.smog-presets { display: flex; flex-wrap: wrap; gap: 6px; }

.smog-presets button {
  padding: 4px 10px;
  border: 1px solid var(--border);
  border-radius: 999px;
  background: var(--surface);
  font-size: 0.82rem;
  font-weight: 600;
  cursor: pointer;
}

.smog-presets button.on { border-color: var(--accent); background: #FFF1E6; }

.smog-presets small { color: var(--muted); font-weight: 500; }

.visually-hidden {
  position: absolute;
  width: 1px;
  height: 1px;
  overflow: hidden;
  clip: rect(0 0 0 0);
  white-space: nowrap;
}

/* TICKER */
.ticker {
  display: flex;
  align-items: center;
  gap: 12px;
  margin: 18px 0 8px;
  padding: 10px 14px;
  border: 1px solid var(--border);
  border-radius: 16px;
  background: var(--surface);
  overflow: hidden;
}

.ticker-label { flex: none; color: #B42318; font-weight: 800; font-size: 0.8rem; letter-spacing: 0.06em; }

.ticker-track {
  overflow: hidden;
  mask-image: linear-gradient(90deg, transparent, #000 6%, #000 94%, transparent);
}

.ticker-items { display: flex; gap: 10px; width: max-content; animation: marquee 38s linear infinite; }

.ticker:hover .ticker-items,
.ticker:focus-within .ticker-items { animation-play-state: paused; }

@keyframes marquee { to { transform: translateX(-50%); } }

.ticker-item {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  padding: 5px 12px 5px 5px;
  border: 1px solid var(--border);
  border-radius: 999px;
  background: var(--surface-2);
  cursor: pointer;
  white-space: nowrap;
  font-weight: 600;
}

.ticker-item small { color: var(--muted); font-weight: 500; }

.pill { min-width: 40px; padding: 2px 8px; border-radius: 999px; font-weight: 800; text-align: center; }

/* STATS */
.stats { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 16px; margin: 14px 0; }

.stat { display: flex; align-items: center; gap: 14px; }

.stat p { margin: 0; }

.num { font-size: 2rem; font-weight: 800; color: var(--brand); line-height: 1.1; }

/* BLOCKS */
.block { padding: 64px 0 8px; }

h2 { margin: 0 0 28px; font-size: clamp(1.5rem, 3vw, 2.2rem); letter-spacing: -0.01em; }

.features { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 18px; }

.feature { display: flex; flex-direction: column; gap: 6px; color: inherit; text-decoration: none; padding: 22px; }

.feature h3 { margin: 6px 0 0; font-size: 1.15rem; }

.feature p { margin: 0; flex: 1; }

.feature-icon {
  display: grid;
  place-items: center;
  width: 92px;
  height: 92px;
  border-radius: 24px;
  background: linear-gradient(145deg, #F3F6FF, #DDE5F5);
  box-shadow: inset 2px 2px 3px #fff, inset -4px -6px 10px rgba(70, 90, 140, 0.16), 0 10px 20px -10px rgba(16, 24, 40, 0.3);
}

.feature:nth-child(3n + 2) .feature-icon { background: linear-gradient(145deg, #FFF4EA, #FFDDC4); }

.go { color: var(--brand); font-weight: 650; margin-top: 8px; }

.steps {
  position: relative;
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 24px;
  margin: 0;
  padding: 0;
  list-style: none;
}

/* animated dashed connector behind the steps */
.steps::before {
  content: '';
  position: absolute;
  top: 56px;
  left: 16%;
  right: 16%;
  height: 3px;
  background: repeating-linear-gradient(90deg, #B9C6E8 0 10px, transparent 10px 20px);
  background-size: 40px 3px;
  animation: dash 1.2s linear infinite;
}

@keyframes dash { to { background-position: 40px 0; } }

.step { position: relative; text-align: center; }

.step-icon {
  display: grid;
  place-items: center;
  width: 112px;
  height: 112px;
  margin: 0 auto 10px;
  border-radius: 50%;
  background: linear-gradient(145deg, #FFFFFF, #E6ECF8);
  box-shadow: inset 2px 2px 4px #fff, inset -5px -7px 12px rgba(70, 90, 140, 0.14), 0 16px 30px -16px rgba(16, 24, 40, 0.35);
}

.step-num {
  position: absolute;
  top: 0;
  left: calc(50% + 30px);
  display: grid;
  place-items: center;
  width: 28px;
  height: 28px;
  border-radius: 50%;
  background: var(--accent);
  color: #2B1200;
  font-weight: 800;
}

.step h3 { margin: 6px 0 4px; }

.step p { margin: 0 auto; max-width: 30ch; }

.schools { display: grid; grid-template-columns: minmax(0, 1fr) minmax(0, 1fr); gap: 32px; align-items: center; }

.checks { margin: 0 0 22px; padding: 0; list-style: none; display: grid; gap: 10px; }

.checks li { padding-left: 30px; position: relative; }

.checks li::before {
  content: '✓';
  position: absolute;
  left: 0;
  top: 1px;
  display: grid;
  place-items: center;
  width: 20px;
  height: 20px;
  border-radius: 50%;
  background: #DDF5E3;
  color: #137333;
  font-size: 0.75rem;
  font-weight: 800;
}

.notice { padding: 22px; }

.notice-head { display: flex; align-items: center; gap: 10px; margin-bottom: 12px; }

.tabs { display: flex; gap: 4px; padding: 4px; border-radius: 12px; background: var(--surface-2); }

.tabs button {
  flex: 1;
  padding: 7px;
  border: 0;
  border-radius: 9px;
  background: transparent;
  color: var(--muted);
  font-weight: 600;
  cursor: pointer;
}

.tabs button.active { background: var(--surface); color: var(--brand); box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1); }

.notice-text { min-height: 230px; margin: 14px 0; white-space: pre-line; line-height: 1.6; }

.wa {
  display: inline-block;
  padding: 8px 14px;
  border-radius: 10px;
  background: #25D366;
  color: #0B2914;
  font-weight: 650;
  text-decoration: none;
}

.cta {
  display: flex;
  align-items: center;
  gap: 20px;
  margin: 72px 0 24px;
  padding: 28px;
  background: linear-gradient(120deg, #E8EEFF, #FFF1E6);
}

.cta h2 { margin: 0 0 4px; font-size: 1.6rem; }

.cta p { margin: 0; }

.cta .btn { margin-left: auto; flex: none; }

.footer { border-top: 1px solid var(--border); padding-top: 16px; }

.footer p { margin: 0 0 6px; }

/* RESPONSIVE */
@media (max-width: 900px) {
  .hero { grid-template-columns: minmax(0, 1fr); min-height: 0; }
  .hero-scene { height: 380px; }
  .features, .stats { grid-template-columns: minmax(0, 1fr); }
  .steps { grid-template-columns: minmax(0, 1fr); }
  .steps::before { display: none; }
  .schools { grid-template-columns: minmax(0, 1fr); }
  .links { display: none; }
  .nav .btn { margin-left: auto; }
  .cta { flex-direction: column; text-align: center; }
  .cta .btn { margin-left: 0; }
}

@media (min-width: 640px) and (max-width: 900px) {
  .features { grid-template-columns: repeat(2, minmax(0, 1fr)); }
}

@media (prefers-reduced-motion: reduce) {
  .ticker-items { animation: none; flex-wrap: wrap; width: auto; }
  .ticker-track { mask-image: none; }
  .steps::before, .dot { animation: none; }
}
</style>
